using Autodesk.Revit.DB;
using goa.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Teigha.Geometry;

namespace PubFuncWt
{
    public static class Teigha
    {
        //public static Line ToLine(this LineSegment3d lineSegment3d)
        //{
        //    XYZ p0 = new XYZ(lineSegment3d.StartPoint.X.MilliMeterToFeet(), lineSegment3d.StartPoint.Y.MilliMeterToFeet(), lineSegment3d.StartPoint.Z.MilliMeterToFeet());
        //    XYZ p1 = new XYZ(lineSegment3d.EndPoint.X.MilliMeterToFeet(), lineSegment3d.EndPoint.Y.MilliMeterToFeet(), lineSegment3d.EndPoint.Z.MilliMeterToFeet());

        //    return Line.CreateBound(p0, p1);
        //}
    }
}
